<?php
/*
Make Sure you include:
ctools_include('modal');
ctools_modal_add_js();
On the pages you put your link.
*/
/**
 * Implements hook_menu().
 */
function start_helper_menu() {
  $items = array();

  $items['mymodule/invoices'] = array(
    'page callback' => 'start_helper_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['mymodule/%ctools_js'] = array(
    'page callback' => 'start_helper_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function start_helper_page() {
  // Load the modal library and add the modal javascript.
  ctools_include('modal');
  ctools_modal_add_js();
  return _start_helper_make_link('Magical modal');
}

/**
 * Ajax menu callback.
 */
function start_helper_callback($ajax) {
  global $user;
  if ($ajax) {
    ctools_include('ajax');
    ctools_include('modal');
    ctools_include('node.pages', 'node', ''); 
  // Create a blank node object here. You can also set values for your custom fields here as well.

    $node = (object) array(
      'uid' => $user->uid, 
      'name' => (isset($user->name) ? $user->name : ''), 
      'type' => 'invoice', 
      'language' => LANGUAGE_NONE,
      );
    $form_state = array(
      'title' => t('Add invoice'),
      'ajax' => TRUE,
    );
    $form_state['build_info']['args'] = array($node);
    // change this to your type node form
    $output = ctools_modal_form_wrapper('invoice_node_form', $form_state);

    $form_state = array(
      'ajax' => TRUE,
      'title' => t('MyModule Modal Form'),
    );

      // Use ctools to generate ajax instructions for the browser to create
      // a form in a modal popup. 

      // If the form has been submitted, there may be additional instructions
      // such as dismissing the modal popup.
    if (!empty($form_state['ajax_commands'])) {
      $output = $form_state['ajax_commands'];
    }

      // Return the ajax instructions to the browser via ajax_render().
    print ajax_render($output);
    drupal_exit();
  }
  else {
    return 'test';
  }
}


function _start_helper_make_link($link_text = '') {
  // Set a default value if no text in supplied.
  if (empty($link_text)) {
    $link_text = 'Magical Modal';
  }

  return '<div id="magical-modal-link">' . l($link_text, 'mymodule/nojs', array('attributes' => array('class' => 'ctools-use-modal'))) . '</div>';
}


